AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Sample SAM Template for AWS
Resources:
  LambdaCDDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LambdaCDDemo
      Handler: functions.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::040251880076:role/MyLambdaRole
      Environment:
        Variables:
          PARAM1: eu-west-1
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get